### ISSUE TITLE
Flash Player in Chrome does not work with Balsamiq Webpage

### ISSUE THREAD

**Issue by dkdndes** [balsamiq/support.balsamiq.com#134]
I am a new user of Balsamiq, the help page forwarded me to a help-text on a sub-domain without a direct option to write to you except here on via Github. I am not sure if that's intended but due to no other documented communication channel (on your help page) for errors please find below my error message:

After using "Add a Mookup" the application produced the following error message:

      Loading myBalsamiq editor...Flash Player 11.2 or later required.

I use 
* Chrome Version 60.0.3112.90 (Offizieller Build) (64-Bit) and an 
* Apple Mac Pro with MacOS High Sierra 10.13

Flash Player support is enabled via chrome://settings/content but still it does not work. 

I do have a paid subscription and would love to make use of it. I don't plan to change my browser because you don't support it. 

Please advise how I to proceed?

**Comment by balsamiqFlorian** [comment]
Hi,

First of all this is not one of our usual channels. You can contact us via email support@balsamiq.com, via our forum (https://forums.balsamiq.com) and via our support contact form here: https://balsamiq.com/company/contact/

Regarding your issue. When you enabled the Flash player did you allow it to run on all sites or does it have to ask?
https://helpx.adobe.com/flash-player/kb/enabling-flash-player-chrome.html
Did you add an exception with the value: *.mybalsamiq.com

If it still does not load the editor after adding the exception can you please click on the "Flash Player 11.2 or later required." link?

If this does not work please let us know via support@balsamiq.com.

**Comment by dkdndes** [comment]
Hi, 

thank you for the quick response and the support-email. 

I added:

      [*.]mybalsamiq.com

and now it works. Please close #134.
Thank you!

**Comment by abdennour** [comment]
The same environment : 

1. Go to `chrome://settings/content/flash`

Then, add `https://[YOUR_USERNAME].mybalsamiq.com` in the whitelist 

<img width="964" alt="screen shot 2017-09-21 at 18 49 00" src="https://user-images.githubusercontent.com/1788384/30705279-a7becd5a-9efd-11e7-9460-2330ef89cf31.png">
