### ISSUE TITLE
problem not yet solve

### ISSUE THREAD

**Issue by zhiyuan94** [balsamiq/support.balsamiq.com#185]
even change the skin image still not able to generate

**Comment by VirginPereira** [comment]
Hi @zhiyuan94,

So sorry for the snag while using myBalsamiq. We are investigating the issue, and the dev team is working on a fix as we speak.

If you need immediate access to a myBalsamiq project, you can [download it](https://support.balsamiq.com/mybalsamiq/mybandb3/#going-from-mybalsamiq-to-mockups-3-for-desktop) and continue to work on it in [Mockups 3 for Desktop](https://balsamiq.com/download) in the meantime.

I can also give you a Mockups 3 for Desktop trial extension in case you already used a trial. Just reach out to support@balsamiq.com and I'll set it up.

Sorry again for the trouble and thanks for bearing with us while we work on fixing this one.

Best,

**Comment by VirginPereira** [comment]
Hi @zhiyuan94 ,

We should be back on track now but please let us know if you still see any issue. 

Sorry again for the trouble and thanks for your patience.

Best,

**Comment by zhiyuan94** [comment]
Hi,


I would like to ask how balsamiq software change skin?


Thank you.


Best Regards,

Zyuan Too


________________________________

**Comment by VirginPereira** [comment]
Hi @zhiyuan94,

The option is located in the **View Menu** inside the editor, as shown below.

<img width="684" alt="skin" src="https://user-images.githubusercontent.com/16241915/34144120-7236733a-e490-11e7-9983-fff189245934.png">

Hope this helps! :)

**Comment by zhiyuan94** [comment]
Hi,


Is desktop version same with web version? Because it seems like getting a little bit different.


[cid:b40aee28-3474-445d-af9f-ff7afffe9133]



Thank you.


Best Regards,

Zyuan Too


________________________________

**Comment by VirginPereira** [comment]
The two products have some differences for now indeed because they are using different versions of our editor but we're in the process of harmonizing all our products.

For now, the **skin** can be changed from the Project Info panel in Mockup 3 for Desktop, as detailed [here](https://docs.balsamiq.com/desktop/skins/).

Please reach out via support@balsamiq.com if you'd like more details about this, we'll be happy to share more information and links if needed.

**Comment by zhiyuan94** [comment]
Hi,


Noted with thanks.


Thank you.


Best Regards,

Zyuan Too


________________________________
